name: Compressed Size

on:
  push:
    branches: [master, next]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: preactjs/compressed-size-action@v2
