# This workflow bumps the package.json version and creates a PR

name: Update package version

on:
  workflow_dispatch:
    inputs:
      semver:
        type: choice
        description: Which semver segment to update
        required: true
        options:
        - major
        - minor
        - patch

jobs:
  upgrade-packages:
    name: Update package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Update version
        run: npm --no-git-tag-version version ${{ github.event.inputs.semver }}
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: 'version/automated'
          title: 'Update package version (automated)'
          commit-message: 'Update package version'
          body: ''
